# Generated by Django 5.0 on 2023-12-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PriorityScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.priorityscale')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('missions', models.ManyToManyField(to='wdmmorpg.mission')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.priorityscale')),
            ],
        ),
        migrations.AddField(
            model_name='priorityscale',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.rank'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.environment')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.priorityscale')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='tasks',
            field=models.ManyToManyField(to='wdmmorpg.task'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('prestige', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('endurance', models.IntegerField(default=100)),
                ('mind', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumables', models.ManyToManyField(blank=True, to='wdmmorpg.consumable')),
                ('tools', models.ManyToManyField(blank=True, to='wdmmorpg.tool')),
                ('transportation_keys', models.ManyToManyField(blank=True, to='wdmmorpg.transportationkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('achievements', models.JSONField(default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.userprofile')),
            ],
        ),
    ]
