# Generated by Django 4.2.6 on 2024-02-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplayer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskplayers', to='wdmmorpg.Project'),
        ),
    ]
