# Generated by Django 5.0 on 2023-12-20 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.AddField(
            model_name='consumable',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumable',
            name='effect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='environment',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='quality',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(default='digital', max_length=100),
        ),
        migrations.AddField(
            model_name='transportationkey',
            name='access_level',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='transportationkey',
            name='type',
            field=models.CharField(default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertaskinteraction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 31, 23, 59, 59), null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertaskinteraction',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 31, 23, 59, 59), null=True)),
                ('achievements', models.JSONField(default=dict)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.userprofile')),
            ],
        ),
    ]
