# Generated by Django 4.2.6 on 2024-02-29 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskplayer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectss', to='wdmmorpg.project'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_points', models.IntegerField(default=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_user', to='wdmmorpg.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_attribute', to='wdmmorpg.attribute'),
        ),
    ]
