# Generated by Django 4.2.6 on 2024-02-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0002_alter_taskplayer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskplayer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='wdmmorpg.project'),
        ),
    ]
