# Generated by Django 4.2.6 on 2024-02-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0004_alter_taskplayer_project'),
    ]

    operations = [

    ]
