# Generated by Django 4.2.6 on 2024-01-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0004_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
