# Generated by Django 4.2.6 on 2024-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0005_task_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='experience_gained',
            field=models.IntegerField(default=0),
        ),
    ]
