# Generated by Django 4.2.6 on 2024-02-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0005_attribute'),
    ]

    operations = [
    ]
