# Generated by Django 4.2.6 on 2024-01-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0006_task_experience_gained'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='wdmmorpg.userprofile'),
        ),
    ]
