# Generated by Django 4.2.6 on 2024-02-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0006_skill_cost_skill_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='skill_attribute', to='wdmmorpg.attribute'),
        ),
    ]
