# Generated by Django 4.2.6 on 2024-02-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0005_skill_cost_skill_gain_attribute_alter_skill_type'),
        ('wdmmorpg', '0007_alter_skill_type'),
    ]

    operations = [
    ]
