# Generated by Django 4.2.6 on 2024-02-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0002_skill_cost_skill_gain_alter_taskplayer_project_and_more'),
        ('wdmmorpg', '0008_merge_20240229_2015'),
    ]

    operations = [
    ]
