# Generated by Django 4.2.6 on 2024-01-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0009_consumable_user_environment_user_mission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='users',
            field=models.ManyToManyField(to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='priorityscale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='priority_scales', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='taskplayer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskplayers', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='transportationkey',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transportation_keys', to='wdmmorpg.userprofile'),
        ),
        migrations.AlterField(
            model_name='usertaskinteraction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usertaskinteractions', to='wdmmorpg.userprofile'),
        ),
    ]
