# Generated by Django 4.2.6 on 2024-01-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.priorityscale'),
        ),
    ]
