version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10 # Updated to your specified version
    commands:
      - echo "Installing dependencies for taskforce"
      - pip install --upgrade pip
      - pip install -r requirements.txt  # Assumes requirements.txt is in the root
      - pip install django-storages
      - pip install boto3
      - pip install psycopg2

  pre_build:
    commands:
      - echo "Running pre-build commands for taskforce"
      - python manage.py migrate --settings=taskforce.settings --noinput  # Updated path
      - python manage.py collectstatic --settings=taskforce.settings --noinput  # Handle static files

  build:
    commands:
      - echo "Build commands for taskforce"
      # Insert any additional build commands if needed later

  post_build:
    commands:
      - echo "taskforce build and deployment completed."

artifacts:
  files:
    - '**/*'  # Adjust if specific files need to be preserved