version: '3.8'

services:
  web:
    build: .
    command: gunicorn taskforce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/taskforce
      - static_volume:/usr/src/taskforce/staticfiles
      - media_volume:/usr/src/taskforce/media
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:Lightvessel100!@db:5432/wdmdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wdmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Lightvessel100!

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
