apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate # Ensure no multiple instances during volume use
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_DB
            value: wdmdb
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgress-secret
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdataa  # Gebruik een subdirectory
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
