apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  password: TGlnaHR2ZXNzZWwxMDAh
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  secret-key: ZGphbmdvLWluc2VjdXJlLUB0M2ZtMHRjMz00aHdsenMldHl2K3kwI3c1eTJfJSgyOS14JGdybGhiNGhfKyt3N293

