# Generated by Django 4.2.6 on 2024-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/shopimage.jpg', upload_to='product_images/'),
        ),
    ]
