# Generated by Django 4.2.6 on 2024-01-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdmmorpg', '0001_initial'),
        ('shop_manager', '0003_order_product_stock_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wdmmorpg.userprofile'),
        ),
    ]
